---
# 9/15 - nginx_configure/tasts/main.yml
# Create role - Shane Mongan & Matt Russell
- name: Copy nginx Config
  copy:
    src: nginx.conf
    dest: /etc/nginx/nginx.con
    mode: 0644

- name: Restart nginx
  service:
    name: nginx
    state: restarted